development: &defaults
  app_site: http://portal.futurewei.ebento.net
  host: portal.futurewei.ebento.net
  my_ebento_link: http://mobile.futurewei.ebento.net
  email_from: noreply@portal.futurewei.ebento.net
  ondeego_smb_login: "PelesendSMB"
  ondeego_smb_password: "peleSMB123"
  use_ondeego: false
  use_mobile_tribe: false
  use_sogo: false
  on_deego_api: https://ondeego.futurewei.ebento.net:8443/appcentral
  mobile_tribe_api: http://mtproxy.futurewei.ebento.net/ws
  ondeego_consumer_key: "Ag=="
  ondeego_consumer_secret: "d+cYHMqMyik3x7lieltd37yMqih9ECvLFHQCju0+gGc="
  wrapper_login: "myapp"
  wrapper_password: "beta"
  wrapper_api: "http://mail.futurewei.ebento.net"
  sogo_url: "https://mail.futurewei.ebento.net/SOGo"
  cas_url: "https://cas.futurewei.ebento.net"
  sogo_email_domaim: futurewei.ebento.net
  #Don't forget change key in rubycas-server config, if aes_key changed
  aes_key: "nK9XUuzzoGeR/Hr/eXFQ0g=="
  session_key: '_eBento_session'
  cookies_domain: 'ebento.net'
  multi_company: false
  help_system_link: http://docs.futurewei.ebento.net/display/eBento
  version: "2.56"


test:
  <<: *defaults
    
production:
  <<: *defaults
  use_ondeego: true
  use_mobile_tribe: true
  use_sogo: true
