development: &defaults
  app_site: http://connections.pelesend.com
  host: connections.pelesend.com
  my_ebento_link: http://mtproxy8.ebento.net
  email_from: noreply@connections.pelesend.com
  ondeego_smb_login: "PelesendSMB"
  ondeego_smb_password: "peleSMB123"
  use_ondeego: false
  use_sogo: false
  use_mobile_tribe: false
  on_deego_api: https://ondeego.futurewei.ebento.net:8443/appcentral
  mobile_tribe_api: http://mtproxy8.mobiletribe.net/ws
  ondeego_consumer_key: "Ag=="
  ondeego_consumer_secret: "d+cYHMqMyik3x7lieltd37yMqih9ECvLFHQCju0+gGc="
  wrapper_login: "myapp"
  wrapper_password: "beta"
  wrapper_api: "http://sogoprd1.pelesend.com"
  sogo_url: "http://sogoprd1.pelesend.com/SOGo"
  cas_url: "http://cas.pelesend.com"
  sogo_email_domaim: pelesend.com
  #Don't forget change key in rubycas-server config, if aes_key changed
  aes_key: "zjwfV8rQt6KsAnXcdtRTtw=="
  session_key: '_test_eBento_session'
  cookies_domain: 'pelesend.com'
  multi_company: false
  help_system_link: http://docs.futurewei.ebento.net/display/eBento
  version: "2.56"

test:
  <<: *defaults

production:
  <<: *defaults
  use_ondeego: true
  use_mobile_tribe: false
  use_sogo: true

